# name: Build and Deploy iOS App

# on:
#   push:
#     tags:
#       - 'v.[0-9]+.[0-9]+.[0-9]+'

# jobs:
#   iOS:
#     name: Build CI (iOS)
#     runs-on: macos-latest

#     # env:
#     #   ANDROID_FIREBASE_APP_ID: ${{ secrets.ANDROID_FIREBASE_APP_ID }}
#     #   IOS_FIREBASE_APP_ID: ${{ secrets.IOS_FIREBASE_APP_ID }}
#     #   FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#     #   MATCH_GIT_BASIC_AUTHORIZATION:  ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}

#     concurrency:
#       group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#       cancel-in-progress: true

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Install Flutter
#       uses: subosito/flutter-action@v2
#       with:
#         flutter-version: '3.22.0'  # Use the latest stable version or specify the version you need
#         channel: 'stable'
#         cache: true

#     - name: Install dependencies
#       run: flutter pub get

#     - name: Install pod
#       run: cd ios && pod install

#     - name: Build IPA
#       run: flutter build ios --release --no-codesign

#     # New step to list directory contents for troubleshooting
#     - name: List build directory
#       run: ls -R build/ios/

#     # runner.app to IPA == https://stackoverflow.com/a/56666092
#     - name: Upload IPA artifact
#       uses: actions/upload-artifact@v4
#       with:
#         name: app-release-ipa
#         path: build/ios/iphoneos/Runner.app 


#     # - name: Upload APK to Firebase App Distribution
#     #   run: |
#     #     wget https://dl.google.com/firebase/appdistribution/appdistribution-cli/latest/linux/firebase-appdistribution-cli-linux.zip
#     #     unzip firebase-appdistribution-cli-linux.zip
#     #     ./firebase-appdistribution --app $ANDROID_FIREBASE_APP_ID --release-notes "New release from GitHub Actions" --token $FIREBASE_TOKEN app/build/outputs/flutter-apk/app-release.apk

#     # - name: Upload IPA to Firebase App Distribution
#     #   run: |
#     #     wget https://dl.google.com/firebase/appdistribution/appdistribution-cli/latest/linux/firebase-appdistribution-cli-linux.zip
#     #     unzip firebase-appdistribution-cli-linux.zip
#     #     ./firebase-appdistribution --app $IOS_FIREBASE_APP_ID --release-notes "New release from GitHub Actions" --token $FIREBASE_TOKEN build/ios/iphoneos/Runner.app




